/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonathaneyster' at '10/24/16 11:02 AM' with Gradle 2.14.1
 *
 * @author jonathaneyster, @date 10/24/16 11:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
